name: Deploy Built React App to EC2

on:
  push:
    branches:
      - deploy-to-aws  # or the branch you use to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Upload Build Folder to EC2 via SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "build/*"
        target: "/home/ec2-user/skillang/build"

    - name: Run Deployment Commands on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo rm -rf /usr/share/nginx/html/*
          sudo cp -r /home/ec2-user/skillang/build/* /usr/share/nginx/html/
          sudo systemctl restart nginx
